begin;

-- Cover every foreign-key column tuple in declared order so deletes and joins do not scan child tables.
create index if not exists ai_budget_periods_budget_policy_id_owner_id_f8a48756_idx on private.ai_budget_periods (budget_policy_id, owner_id);
create index if not exists ai_budget_reservations_agent_run_id_owner_id_5786098c_idx on private.ai_budget_reservations (agent_run_id, owner_id);
create index if not exists ai_budget_reservations_budget_policy_id_owner_id_5d28090b_idx on private.ai_budget_reservations (budget_policy_id, owner_id);
create index if not exists ai_budget_reservations_daily_period_id_owner_id_9261764a_idx on private.ai_budget_reservations (daily_period_id, owner_id);
create index if not exists ai_budget_reservations_experiment_id_owner_id_ff6e0666_idx on private.ai_budget_reservations (experiment_id, owner_id);
create index if not exists ai_budget_reservations_lifetime_period_id_owner__4454fb75_idx on private.ai_budget_reservations (lifetime_period_id, owner_id);
create index if not exists ai_budget_reservations_monthly_period_id_owner_i_40c70a34_idx on private.ai_budget_reservations (monthly_period_id, owner_id);
create index if not exists ai_quota_periods_budget_policy_id_owner_id_60d24347_idx on private.ai_quota_periods (budget_policy_id, owner_id);
create index if not exists ai_reservation_quotas_quota_period_id_owner_id_2f884710_idx on private.ai_reservation_quotas (quota_period_id, owner_id);
create index if not exists ai_reservation_quotas_reservation_id_owner_id_913f9a42_idx on private.ai_reservation_quotas (reservation_id, owner_id);
create index if not exists ai_usage_events_agent_run_id_owner_id_76c1fcb0_idx on private.ai_usage_events (agent_run_id, owner_id);
create index if not exists ai_usage_events_experiment_id_owner_id_874b0554_idx on private.ai_usage_events (experiment_id, owner_id);
create index if not exists ai_usage_events_reservation_id_owner_id_8479dccf_idx on private.ai_usage_events (reservation_id, owner_id);
create index if not exists audit_log_experiment_id_owner_id_e973e5d4_idx on private.audit_log (experiment_id, owner_id);
create index if not exists cash_ledger_entries_simulation_account_id_experi_726d57f5_idx on private.cash_ledger_entries (simulation_account_id, experiment_id, owner_id);
create index if not exists dead_letter_events_raw_source_event_id_owner_id_2404cf42_idx on private.dead_letter_events (raw_source_event_id, owner_id);
create index if not exists scheduler_runs_experiment_id_owner_id_b307795d_idx on private.scheduler_runs (experiment_id, owner_id);
create index if not exists scheduler_slots_experiment_id_owner_id_bce8cf63_idx on private.scheduler_slots (experiment_id, owner_id);
create index if not exists agent_decisions_agent_run_id_owner_id_c37900ad_idx on public.agent_decisions (agent_run_id, owner_id);
create index if not exists agent_decisions_context_snapshot_id_owner_id_42984170_idx on public.agent_decisions (context_snapshot_id, owner_id);
create index if not exists agent_decisions_experiment_id_owner_id_c96ca82b_idx on public.agent_decisions (experiment_id, owner_id);
create index if not exists agent_runs_experiment_id_owner_id_68509329_idx on public.agent_runs (experiment_id, owner_id);
create index if not exists agent_runs_prompt_version_id_owner_id_0801cf46_idx on public.agent_runs (prompt_version_id, owner_id);
create index if not exists agent_runs_scheduler_run_id_owner_id_dc067123_idx on public.agent_runs (scheduler_run_id, owner_id);
create index if not exists agent_tool_calls_agent_run_id_owner_id_2844200c_idx on public.agent_tool_calls (agent_run_id, owner_id);
create index if not exists borrow_availability_instrument_id_8ab0224a_idx on public.borrow_availability (instrument_id);
create index if not exists borrow_costs_instrument_id_d7113b32_idx on public.borrow_costs (instrument_id);
create index if not exists budget_alerts_budget_period_id_owner_id_24de6a1d_idx on public.budget_alerts (budget_period_id, owner_id);
create index if not exists corporate_action_applications_corporate_action_i_9600c92f_idx on public.corporate_action_applications (corporate_action_id, owner_id);
create index if not exists corporate_action_applications_simulation_account_5634eb22_idx on public.corporate_action_applications (simulation_account_id, experiment_id, owner_id);
create index if not exists corporate_actions_instrument_id_942be05e_idx on public.corporate_actions (instrument_id);
create index if not exists decision_context_snapshots_agent_run_id_owner_id_36ed26aa_idx on public.decision_context_snapshots (agent_run_id, owner_id);
create index if not exists decision_context_snapshots_experiment_id_owner_i_a0834440_idx on public.decision_context_snapshots (experiment_id, owner_id);
create index if not exists decision_context_snapshots_experiment_version_id_97e87b3f_idx on public.decision_context_snapshots (experiment_version_id, owner_id);
create index if not exists decision_context_snapshots_portfolio_snapshot_id_8ab3beef_idx on public.decision_context_snapshots (portfolio_snapshot_id, owner_id);
create index if not exists decision_context_snapshots_strategy_version_id_o_54f9b62f_idx on public.decision_context_snapshots (strategy_version_id, owner_id);
create index if not exists decision_evidence_decision_id_owner_id_d0f627a1_idx on public.decision_evidence (decision_id, owner_id);
create index if not exists event_entities_event_revision_id_owner_id_9d87cd65_idx on public.event_entities (event_revision_id, owner_id);
create index if not exists event_features_event_revision_id_owner_id_3382f77c_idx on public.event_features (event_revision_id, owner_id);
create index if not exists event_instrument_links_event_revision_id_owner_i_f5b25409_idx on public.event_instrument_links (event_revision_id, owner_id);
create index if not exists event_revisions_event_id_owner_id_f034084b_idx on public.event_revisions (event_id, owner_id);
create index if not exists event_scores_event_revision_id_owner_id_91b6dd7d_idx on public.event_scores (event_revision_id, owner_id);
create index if not exists experiment_benchmarks_experiment_id_owner_id_f2b01ca6_idx on public.experiment_benchmarks (experiment_id, owner_id);
create index if not exists experiment_status_events_experiment_id_owner_id_1c870495_idx on public.experiment_status_events (experiment_id, owner_id);
create index if not exists experiment_versions_budget_policy_id_owner_id_64001e29_idx on public.experiment_versions (budget_policy_id, owner_id);
create index if not exists experiment_versions_knowledge_corpus_version_id__c0968164_idx on public.experiment_versions (knowledge_corpus_version_id, owner_id);
create index if not exists experiment_versions_data_source_config_version_i_2d639c31_idx on public.experiment_versions (data_source_config_version_id, owner_id);
create index if not exists experiment_versions_experiment_id_owner_id_234423bf_idx on public.experiment_versions (experiment_id, owner_id);
create index if not exists experiment_versions_market_universe_id_owner_id_2f3566f8_idx on public.experiment_versions (market_universe_id, owner_id);
create index if not exists experiment_versions_model_routing_version_id_own_1cec093f_idx on public.experiment_versions (model_routing_version_id, owner_id);
create index if not exists experiment_versions_agent_prompt_version_id_owne_b28ebfe8_idx on public.experiment_versions (agent_prompt_version_id, owner_id);
create index if not exists experiment_versions_risk_config_version_id_owner_c60cb460_idx on public.experiment_versions (risk_config_version_id, owner_id);
create index if not exists experiment_versions_simulator_config_version_id__d5371c89_idx on public.experiment_versions (simulator_config_version_id, owner_id);
create index if not exists experiments_locked_version_id_owner_id_4088dba6_idx on public.experiments (locked_version_id, owner_id);
create index if not exists fill_market_data_refs_fill_id_owner_id_d91d11a5_idx on public.fill_market_data_refs (fill_id, owner_id);
create index if not exists fills_order_id_experiment_id_owner_id_1cf1e8a1_idx on public.fills (order_id, experiment_id, owner_id);
create index if not exists fills_simulation_account_id_experiment_id_owner__6da703a4_idx on public.fills (simulation_account_id, experiment_id, owner_id);
create index if not exists fills_simulator_config_version_id_owner_id_bf9b0e7a_idx on public.fills (simulator_config_version_id, owner_id);
create index if not exists knowledge_chunks_document_version_id_owner_id_2178e47e_idx on public.knowledge_chunks (document_version_id, owner_id);
create index if not exists knowledge_corpus_members_corpus_version_id_owner_dbabb922_idx on public.knowledge_corpus_members (corpus_version_id, owner_id);
create index if not exists knowledge_corpus_members_document_version_id_own_dca37f6b_idx on public.knowledge_corpus_members (document_version_id, owner_id);
create index if not exists knowledge_document_versions_document_id_owner_id_5c2dff1c_idx on public.knowledge_document_versions (document_id, owner_id);
create index if not exists knowledge_documents_knowledge_source_id_owner_id_2c8958b8_idx on public.knowledge_documents (knowledge_source_id, owner_id);
create index if not exists lot_allocations_closing_fill_id_owner_id_429b2eea_idx on public.lot_allocations (closing_fill_id, owner_id);
create index if not exists lot_allocations_lot_id_owner_id_8d168de8_idx on public.lot_allocations (lot_id, owner_id);
create index if not exists margin_snapshots_simulation_account_id_experimen_dc499278_idx on public.margin_snapshots (simulation_account_id, experiment_id, owner_id);
create index if not exists market_bars_instrument_id_7f830df4_idx on public.market_bars (instrument_id);
create index if not exists market_quotes_instrument_id_292c1066_idx on public.market_quotes (instrument_id);
create index if not exists market_universe_members_universe_id_owner_id_2695d4b2_idx on public.market_universe_members (universe_id, owner_id);
create index if not exists memory_summaries_agent_run_id_owner_id_2d89f01c_idx on public.memory_summaries (agent_run_id, owner_id);
create index if not exists memory_summaries_experiment_id_owner_id_82c57b6f_idx on public.memory_summaries (experiment_id, owner_id);
create index if not exists model_routing_events_agent_run_id_owner_id_d8ed0f74_idx on public.model_routing_events (agent_run_id, owner_id);
create index if not exists model_routing_events_experiment_id_owner_id_6b3a8b53_idx on public.model_routing_events (experiment_id, owner_id);
create index if not exists order_status_events_order_id_experiment_id_owner_868efec4_idx on public.order_status_events (order_id, experiment_id, owner_id);
create index if not exists orders_agent_decision_id_owner_id_e0bdfb86_idx on public.orders (agent_decision_id, owner_id);
create index if not exists orders_experiment_version_id_owner_id_d312be2d_idx on public.orders (experiment_version_id, owner_id);
create index if not exists orders_simulation_account_id_experiment_id_owner_9a4c7c35_idx on public.orders (simulation_account_id, experiment_id, owner_id);
create index if not exists pattern_evidence_decision_id_owner_id_a1a1d882_idx on public.pattern_evidence (decision_id, owner_id);
create index if not exists pattern_evidence_outcome_id_owner_id_fb2ac302_idx on public.pattern_evidence (outcome_id, owner_id);
create index if not exists pattern_evidence_pattern_id_owner_id_7e046a70_idx on public.pattern_evidence (pattern_id, owner_id);
create index if not exists pattern_hypotheses_experiment_id_owner_id_f8f788a1_idx on public.pattern_hypotheses (experiment_id, owner_id);
create index if not exists portfolio_snapshots_simulation_account_id_experi_59b14204_idx on public.portfolio_snapshots (simulation_account_id, experiment_id, owner_id);
create index if not exists position_lots_instrument_id_ba0001fe_idx on public.position_lots (instrument_id);
create index if not exists position_lots_opening_fill_id_owner_id_3cdb3df6_idx on public.position_lots (opening_fill_id, owner_id);
create index if not exists position_lots_simulation_account_id_experiment_i_9a9bd030_idx on public.position_lots (simulation_account_id, experiment_id, owner_id);
create index if not exists positions_simulation_account_id_experiment_id_ow_8a830225_idx on public.positions (simulation_account_id, experiment_id, owner_id);
create index if not exists risk_events_agent_decision_id_owner_id_902eb2ae_idx on public.risk_events (agent_decision_id, owner_id);
create index if not exists risk_events_experiment_id_owner_id_2eb3d0e1_idx on public.risk_events (experiment_id, owner_id);
create index if not exists risk_events_order_id_experiment_id_owner_id_842728f2_idx on public.risk_events (order_id, experiment_id, owner_id);
create index if not exists simulation_accounts_experiment_id_owner_id_773064ef_idx on public.simulation_accounts (experiment_id, owner_id);
create index if not exists simulator_runs_experiment_id_owner_id_a2f029f4_idx on public.simulator_runs (experiment_id, owner_id);
create index if not exists simulator_runs_simulator_config_version_id_owner_578a6f95_idx on public.simulator_runs (simulator_config_version_id, owner_id);
create index if not exists strategy_assignments_experiment_id_owner_id_e13fd1eb_idx on public.strategy_assignments (experiment_id, owner_id);
create index if not exists strategy_assignments_strategy_version_id_owner_i_08a0ee62_idx on public.strategy_assignments (strategy_version_id, owner_id);
create index if not exists trade_outcomes_decision_id_owner_id_2046c42d_idx on public.trade_outcomes (decision_id, owner_id);

commit;
